/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpendRouteImport } from './routes/spend'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'
import { Route as SessionsThreadIdRouteImport } from './routes/sessions.$threadId'
import { Route as ApiWebhooksRouteImport } from './routes/api.webhooks'
import { Route as ApiToolsRouteImport } from './routes/api.tools'
import { Route as ApiTailRouteImport } from './routes/api.tail'
import { Route as ApiSessionsRouteImport } from './routes/api.sessions'
import { Route as ApiSchedulesRouteImport } from './routes/api.schedules'
import { Route as ApiRunsRouteImport } from './routes/api.runs'
import { Route as ApiRunRouteImport } from './routes/api.run'
import { Route as ApiRosterRouteImport } from './routes/api.roster'
import { Route as ApiReplayRouteImport } from './routes/api.replay'
import { Route as ApiMetaRouteImport } from './routes/api.meta'
import { Route as ApiMemoryRouteImport } from './routes/api.memory'
import { Route as ApiInjectRouteImport } from './routes/api.inject'
import { Route as ApiHostsRouteImport } from './routes/api.hosts'
import { Route as ApiConfigRouteImport } from './routes/api.config'
import { Route as ApiAgentRouteImport } from './routes/api.agent'
import { Route as ApiWebhooksTokenRouteImport } from './routes/api.webhooks.$token'
import { Route as ApiHarnessSplatRouteImport } from './routes/api.harness.$'
import { Route as ApiDevOfflineRouteImport } from './routes/api.dev.offline'

const SpendRoute = SpendRouteImport.update({
  id: '/spend',
  path: '/spend',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsThreadIdRoute = SessionsThreadIdRouteImport.update({
  id: '/sessions/$threadId',
  path: '/sessions/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksRoute = ApiWebhooksRouteImport.update({
  id: '/api/webhooks',
  path: '/api/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsRoute = ApiToolsRouteImport.update({
  id: '/api/tools',
  path: '/api/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTailRoute = ApiTailRouteImport.update({
  id: '/api/tail',
  path: '/api/tail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchedulesRoute = ApiSchedulesRouteImport.update({
  id: '/api/schedules',
  path: '/api/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRoute = ApiRunsRouteImport.update({
  id: '/api/runs',
  path: '/api/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunRoute = ApiRunRouteImport.update({
  id: '/api/run',
  path: '/api/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRosterRoute = ApiRosterRouteImport.update({
  id: '/api/roster',
  path: '/api/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReplayRoute = ApiReplayRouteImport.update({
  id: '/api/replay',
  path: '/api/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaRoute = ApiMetaRouteImport.update({
  id: '/api/meta',
  path: '/api/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryRoute = ApiMemoryRouteImport.update({
  id: '/api/memory',
  path: '/api/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInjectRoute = ApiInjectRouteImport.update({
  id: '/api/inject',
  path: '/api/inject',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHostsRoute = ApiHostsRouteImport.update({
  id: '/api/hosts',
  path: '/api/hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksTokenRoute = ApiWebhooksTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => ApiWebhooksRoute,
} as any)
const ApiHarnessSplatRoute = ApiHarnessSplatRouteImport.update({
  id: '/api/harness/$',
  path: '/api/harness/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevOfflineRoute = ApiDevOfflineRouteImport.update({
  id: '/api/dev/offline',
  path: '/api/dev/offline',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/config': typeof ConfigRoute
  '/history': typeof HistoryRoute
  '/spend': typeof SpendRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/config': typeof ApiConfigRoute
  '/api/hosts': typeof ApiHostsRoute
  '/api/inject': typeof ApiInjectRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/meta': typeof ApiMetaRoute
  '/api/replay': typeof ApiReplayRoute
  '/api/roster': typeof ApiRosterRoute
  '/api/run': typeof ApiRunRoute
  '/api/runs': typeof ApiRunsRoute
  '/api/schedules': typeof ApiSchedulesRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/tail': typeof ApiTailRoute
  '/api/tools': typeof ApiToolsRoute
  '/api/webhooks': typeof ApiWebhooksRouteWithChildren
  '/sessions/$threadId': typeof SessionsThreadIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/api/dev/offline': typeof ApiDevOfflineRoute
  '/api/harness/$': typeof ApiHarnessSplatRoute
  '/api/webhooks/$token': typeof ApiWebhooksTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/config': typeof ConfigRoute
  '/history': typeof HistoryRoute
  '/spend': typeof SpendRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/config': typeof ApiConfigRoute
  '/api/hosts': typeof ApiHostsRoute
  '/api/inject': typeof ApiInjectRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/meta': typeof ApiMetaRoute
  '/api/replay': typeof ApiReplayRoute
  '/api/roster': typeof ApiRosterRoute
  '/api/run': typeof ApiRunRoute
  '/api/runs': typeof ApiRunsRoute
  '/api/schedules': typeof ApiSchedulesRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/tail': typeof ApiTailRoute
  '/api/tools': typeof ApiToolsRoute
  '/api/webhooks': typeof ApiWebhooksRouteWithChildren
  '/sessions/$threadId': typeof SessionsThreadIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/api/dev/offline': typeof ApiDevOfflineRoute
  '/api/harness/$': typeof ApiHarnessSplatRoute
  '/api/webhooks/$token': typeof ApiWebhooksTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/config': typeof ConfigRoute
  '/history': typeof HistoryRoute
  '/spend': typeof SpendRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/config': typeof ApiConfigRoute
  '/api/hosts': typeof ApiHostsRoute
  '/api/inject': typeof ApiInjectRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/meta': typeof ApiMetaRoute
  '/api/replay': typeof ApiReplayRoute
  '/api/roster': typeof ApiRosterRoute
  '/api/run': typeof ApiRunRoute
  '/api/runs': typeof ApiRunsRoute
  '/api/schedules': typeof ApiSchedulesRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/tail': typeof ApiTailRoute
  '/api/tools': typeof ApiToolsRoute
  '/api/webhooks': typeof ApiWebhooksRouteWithChildren
  '/sessions/$threadId': typeof SessionsThreadIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/api/dev/offline': typeof ApiDevOfflineRoute
  '/api/harness/$': typeof ApiHarnessSplatRoute
  '/api/webhooks/$token': typeof ApiWebhooksTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/config'
    | '/history'
    | '/spend'
    | '/api/agent'
    | '/api/config'
    | '/api/hosts'
    | '/api/inject'
    | '/api/memory'
    | '/api/meta'
    | '/api/replay'
    | '/api/roster'
    | '/api/run'
    | '/api/runs'
    | '/api/schedules'
    | '/api/sessions'
    | '/api/tail'
    | '/api/tools'
    | '/api/webhooks'
    | '/sessions/$threadId'
    | '/teams/$teamId'
    | '/api/dev/offline'
    | '/api/harness/$'
    | '/api/webhooks/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/config'
    | '/history'
    | '/spend'
    | '/api/agent'
    | '/api/config'
    | '/api/hosts'
    | '/api/inject'
    | '/api/memory'
    | '/api/meta'
    | '/api/replay'
    | '/api/roster'
    | '/api/run'
    | '/api/runs'
    | '/api/schedules'
    | '/api/sessions'
    | '/api/tail'
    | '/api/tools'
    | '/api/webhooks'
    | '/sessions/$threadId'
    | '/teams/$teamId'
    | '/api/dev/offline'
    | '/api/harness/$'
    | '/api/webhooks/$token'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/config'
    | '/history'
    | '/spend'
    | '/api/agent'
    | '/api/config'
    | '/api/hosts'
    | '/api/inject'
    | '/api/memory'
    | '/api/meta'
    | '/api/replay'
    | '/api/roster'
    | '/api/run'
    | '/api/runs'
    | '/api/schedules'
    | '/api/sessions'
    | '/api/tail'
    | '/api/tools'
    | '/api/webhooks'
    | '/sessions/$threadId'
    | '/teams/$teamId'
    | '/api/dev/offline'
    | '/api/harness/$'
    | '/api/webhooks/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ConfigRoute: typeof ConfigRoute
  HistoryRoute: typeof HistoryRoute
  SpendRoute: typeof SpendRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiHostsRoute: typeof ApiHostsRoute
  ApiInjectRoute: typeof ApiInjectRoute
  ApiMemoryRoute: typeof ApiMemoryRoute
  ApiMetaRoute: typeof ApiMetaRoute
  ApiReplayRoute: typeof ApiReplayRoute
  ApiRosterRoute: typeof ApiRosterRoute
  ApiRunRoute: typeof ApiRunRoute
  ApiRunsRoute: typeof ApiRunsRoute
  ApiSchedulesRoute: typeof ApiSchedulesRoute
  ApiSessionsRoute: typeof ApiSessionsRoute
  ApiTailRoute: typeof ApiTailRoute
  ApiToolsRoute: typeof ApiToolsRoute
  ApiWebhooksRoute: typeof ApiWebhooksRouteWithChildren
  SessionsThreadIdRoute: typeof SessionsThreadIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  ApiDevOfflineRoute: typeof ApiDevOfflineRoute
  ApiHarnessSplatRoute: typeof ApiHarnessSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spend': {
      id: '/spend'
      path: '/spend'
      fullPath: '/spend'
      preLoaderRoute: typeof SpendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$threadId': {
      id: '/sessions/$threadId'
      path: '/sessions/$threadId'
      fullPath: '/sessions/$threadId'
      preLoaderRoute: typeof SessionsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks': {
      id: '/api/webhooks'
      path: '/api/webhooks'
      fullPath: '/api/webhooks'
      preLoaderRoute: typeof ApiWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools': {
      id: '/api/tools'
      path: '/api/tools'
      fullPath: '/api/tools'
      preLoaderRoute: typeof ApiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tail': {
      id: '/api/tail'
      path: '/api/tail'
      fullPath: '/api/tail'
      preLoaderRoute: typeof ApiTailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schedules': {
      id: '/api/schedules'
      path: '/api/schedules'
      fullPath: '/api/schedules'
      preLoaderRoute: typeof ApiSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs': {
      id: '/api/runs'
      path: '/api/runs'
      fullPath: '/api/runs'
      preLoaderRoute: typeof ApiRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run': {
      id: '/api/run'
      path: '/api/run'
      fullPath: '/api/run'
      preLoaderRoute: typeof ApiRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roster': {
      id: '/api/roster'
      path: '/api/roster'
      fullPath: '/api/roster'
      preLoaderRoute: typeof ApiRosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/replay': {
      id: '/api/replay'
      path: '/api/replay'
      fullPath: '/api/replay'
      preLoaderRoute: typeof ApiReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta': {
      id: '/api/meta'
      path: '/api/meta'
      fullPath: '/api/meta'
      preLoaderRoute: typeof ApiMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory': {
      id: '/api/memory'
      path: '/api/memory'
      fullPath: '/api/memory'
      preLoaderRoute: typeof ApiMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inject': {
      id: '/api/inject'
      path: '/api/inject'
      fullPath: '/api/inject'
      preLoaderRoute: typeof ApiInjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hosts': {
      id: '/api/hosts'
      path: '/api/hosts'
      fullPath: '/api/hosts'
      preLoaderRoute: typeof ApiHostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/$token': {
      id: '/api/webhooks/$token'
      path: '/$token'
      fullPath: '/api/webhooks/$token'
      preLoaderRoute: typeof ApiWebhooksTokenRouteImport
      parentRoute: typeof ApiWebhooksRoute
    }
    '/api/harness/$': {
      id: '/api/harness/$'
      path: '/api/harness/$'
      fullPath: '/api/harness/$'
      preLoaderRoute: typeof ApiHarnessSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/offline': {
      id: '/api/dev/offline'
      path: '/api/dev/offline'
      fullPath: '/api/dev/offline'
      preLoaderRoute: typeof ApiDevOfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiWebhooksRouteChildren {
  ApiWebhooksTokenRoute: typeof ApiWebhooksTokenRoute
}

const ApiWebhooksRouteChildren: ApiWebhooksRouteChildren = {
  ApiWebhooksTokenRoute: ApiWebhooksTokenRoute,
}

const ApiWebhooksRouteWithChildren = ApiWebhooksRoute._addFileChildren(
  ApiWebhooksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ConfigRoute: ConfigRoute,
  HistoryRoute: HistoryRoute,
  SpendRoute: SpendRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiHostsRoute: ApiHostsRoute,
  ApiInjectRoute: ApiInjectRoute,
  ApiMemoryRoute: ApiMemoryRoute,
  ApiMetaRoute: ApiMetaRoute,
  ApiReplayRoute: ApiReplayRoute,
  ApiRosterRoute: ApiRosterRoute,
  ApiRunRoute: ApiRunRoute,
  ApiRunsRoute: ApiRunsRoute,
  ApiSchedulesRoute: ApiSchedulesRoute,
  ApiSessionsRoute: ApiSessionsRoute,
  ApiTailRoute: ApiTailRoute,
  ApiToolsRoute: ApiToolsRoute,
  ApiWebhooksRoute: ApiWebhooksRouteWithChildren,
  SessionsThreadIdRoute: SessionsThreadIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  ApiDevOfflineRoute: ApiDevOfflineRoute,
  ApiHarnessSplatRoute: ApiHarnessSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
