/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpendRouteImport } from './routes/spend'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsThreadIdRouteImport } from './routes/sessions.$threadId'
import { Route as ApiSessionsRouteImport } from './routes/api.sessions'
import { Route as ApiRunsRouteImport } from './routes/api.runs'
import { Route as ApiReplayRouteImport } from './routes/api.replay'
import { Route as ApiHostsRouteImport } from './routes/api.hosts'
import { Route as ApiConfigRouteImport } from './routes/api.config'
import { Route as ApiAgentRouteImport } from './routes/api.agent'
import { Route as ApiHarnessSplatRouteImport } from './routes/api.harness.$'

const SpendRoute = SpendRouteImport.update({
  id: '/spend',
  path: '/spend',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsThreadIdRoute = SessionsThreadIdRouteImport.update({
  id: '/sessions/$threadId',
  path: '/sessions/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRoute = ApiRunsRouteImport.update({
  id: '/api/runs',
  path: '/api/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReplayRoute = ApiReplayRouteImport.update({
  id: '/api/replay',
  path: '/api/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHostsRoute = ApiHostsRouteImport.update({
  id: '/api/hosts',
  path: '/api/hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHarnessSplatRoute = ApiHarnessSplatRouteImport.update({
  id: '/api/harness/$',
  path: '/api/harness/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/history': typeof HistoryRoute
  '/spend': typeof SpendRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/config': typeof ApiConfigRoute
  '/api/hosts': typeof ApiHostsRoute
  '/api/replay': typeof ApiReplayRoute
  '/api/runs': typeof ApiRunsRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/sessions/$threadId': typeof SessionsThreadIdRoute
  '/api/harness/$': typeof ApiHarnessSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/history': typeof HistoryRoute
  '/spend': typeof SpendRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/config': typeof ApiConfigRoute
  '/api/hosts': typeof ApiHostsRoute
  '/api/replay': typeof ApiReplayRoute
  '/api/runs': typeof ApiRunsRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/sessions/$threadId': typeof SessionsThreadIdRoute
  '/api/harness/$': typeof ApiHarnessSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/history': typeof HistoryRoute
  '/spend': typeof SpendRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/config': typeof ApiConfigRoute
  '/api/hosts': typeof ApiHostsRoute
  '/api/replay': typeof ApiReplayRoute
  '/api/runs': typeof ApiRunsRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/sessions/$threadId': typeof SessionsThreadIdRoute
  '/api/harness/$': typeof ApiHarnessSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/history'
    | '/spend'
    | '/api/agent'
    | '/api/config'
    | '/api/hosts'
    | '/api/replay'
    | '/api/runs'
    | '/api/sessions'
    | '/sessions/$threadId'
    | '/api/harness/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config'
    | '/history'
    | '/spend'
    | '/api/agent'
    | '/api/config'
    | '/api/hosts'
    | '/api/replay'
    | '/api/runs'
    | '/api/sessions'
    | '/sessions/$threadId'
    | '/api/harness/$'
  id:
    | '__root__'
    | '/'
    | '/config'
    | '/history'
    | '/spend'
    | '/api/agent'
    | '/api/config'
    | '/api/hosts'
    | '/api/replay'
    | '/api/runs'
    | '/api/sessions'
    | '/sessions/$threadId'
    | '/api/harness/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigRoute: typeof ConfigRoute
  HistoryRoute: typeof HistoryRoute
  SpendRoute: typeof SpendRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiHostsRoute: typeof ApiHostsRoute
  ApiReplayRoute: typeof ApiReplayRoute
  ApiRunsRoute: typeof ApiRunsRoute
  ApiSessionsRoute: typeof ApiSessionsRoute
  SessionsThreadIdRoute: typeof SessionsThreadIdRoute
  ApiHarnessSplatRoute: typeof ApiHarnessSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spend': {
      id: '/spend'
      path: '/spend'
      fullPath: '/spend'
      preLoaderRoute: typeof SpendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$threadId': {
      id: '/sessions/$threadId'
      path: '/sessions/$threadId'
      fullPath: '/sessions/$threadId'
      preLoaderRoute: typeof SessionsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs': {
      id: '/api/runs'
      path: '/api/runs'
      fullPath: '/api/runs'
      preLoaderRoute: typeof ApiRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/replay': {
      id: '/api/replay'
      path: '/api/replay'
      fullPath: '/api/replay'
      preLoaderRoute: typeof ApiReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hosts': {
      id: '/api/hosts'
      path: '/api/hosts'
      fullPath: '/api/hosts'
      preLoaderRoute: typeof ApiHostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/harness/$': {
      id: '/api/harness/$'
      path: '/api/harness/$'
      fullPath: '/api/harness/$'
      preLoaderRoute: typeof ApiHarnessSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigRoute: ConfigRoute,
  HistoryRoute: HistoryRoute,
  SpendRoute: SpendRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiHostsRoute: ApiHostsRoute,
  ApiReplayRoute: ApiReplayRoute,
  ApiRunsRoute: ApiRunsRoute,
  ApiSessionsRoute: ApiSessionsRoute,
  SessionsThreadIdRoute: SessionsThreadIdRoute,
  ApiHarnessSplatRoute: ApiHarnessSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
