/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsThreadIdRouteImport } from './routes/sessions.$threadId'
import { Route as ApiSessionsRouteImport } from './routes/api.sessions'
import { Route as ApiHostsRouteImport } from './routes/api.hosts'
import { Route as ApiAgentRouteImport } from './routes/api.agent'
import { Route as ApiHarnessSplatRouteImport } from './routes/api.harness.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsThreadIdRoute = SessionsThreadIdRouteImport.update({
  id: '/sessions/$threadId',
  path: '/sessions/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHostsRoute = ApiHostsRouteImport.update({
  id: '/api/hosts',
  path: '/api/hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHarnessSplatRoute = ApiHarnessSplatRouteImport.update({
  id: '/api/harness/$',
  path: '/api/harness/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/hosts': typeof ApiHostsRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/sessions/$threadId': typeof SessionsThreadIdRoute
  '/api/harness/$': typeof ApiHarnessSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/hosts': typeof ApiHostsRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/sessions/$threadId': typeof SessionsThreadIdRoute
  '/api/harness/$': typeof ApiHarnessSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/hosts': typeof ApiHostsRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/sessions/$threadId': typeof SessionsThreadIdRoute
  '/api/harness/$': typeof ApiHarnessSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/agent'
    | '/api/hosts'
    | '/api/sessions'
    | '/sessions/$threadId'
    | '/api/harness/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/agent'
    | '/api/hosts'
    | '/api/sessions'
    | '/sessions/$threadId'
    | '/api/harness/$'
  id:
    | '__root__'
    | '/'
    | '/api/agent'
    | '/api/hosts'
    | '/api/sessions'
    | '/sessions/$threadId'
    | '/api/harness/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiHostsRoute: typeof ApiHostsRoute
  ApiSessionsRoute: typeof ApiSessionsRoute
  SessionsThreadIdRoute: typeof SessionsThreadIdRoute
  ApiHarnessSplatRoute: typeof ApiHarnessSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$threadId': {
      id: '/sessions/$threadId'
      path: '/sessions/$threadId'
      fullPath: '/sessions/$threadId'
      preLoaderRoute: typeof SessionsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hosts': {
      id: '/api/hosts'
      path: '/api/hosts'
      fullPath: '/api/hosts'
      preLoaderRoute: typeof ApiHostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/harness/$': {
      id: '/api/harness/$'
      path: '/api/harness/$'
      fullPath: '/api/harness/$'
      preLoaderRoute: typeof ApiHarnessSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiHostsRoute: ApiHostsRoute,
  ApiSessionsRoute: ApiSessionsRoute,
  SessionsThreadIdRoute: SessionsThreadIdRoute,
  ApiHarnessSplatRoute: ApiHarnessSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
